name: Deploy Frontend
on: 
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: Docker build -t ${{ secrets.DOCKER_USERNAME }/react-docker:ci -f Dockerfile.dev .

      - name: Run tests inside container
      # --rm removes container after exit; :ci tag to be explicit that this is CI-built image
        run: docker run -rm -r CI=true ${{ secrets.DOCKER_USERNAME }}/react-docker:ci npm test


